services:
  db:
    container_name: customer_service
    image: postgres
    environment:
      POSTRES_USER: F
      POSTGRES_PASSWORD: S
      PGDATA: /data/postgres

    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db:
